-- phpMyAdmin SQL Dump
-- version 5.1.3
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 30, 2022 at 02:10 PM
-- Server version: 10.4.22-MariaDB
-- PHP Version: 7.4.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `ghostwriting`
--

-- --------------------------------------------------------

--
-- Table structure for table `about_pages`
--

CREATE TABLE `about_pages` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name_de` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description_de` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug_de` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `about_pages`
--

INSERT INTO `about_pages` (`id`, `name`, `name_de`, `description_de`, `description`, `slug`, `slug_de`) VALUES
(1, 'Company', 'Unternehmen', 'lorem', 'lorem', 'company', 'company-de'),
(2, 'Know-how', 'Know-how', 'lorem', 'lorem', 'know-how', 'know-how-de'),
(3, 'Quality Assurance', 'Qualitätssicherung', 'lorem', 'lorem', 'quality-assurance', 'quality-assurance-de'),
(4, 'PerFitS – Perfect Fit Solutions', 'PerFitS – Perfect Fit Solutions', 'lorem', 'lorem', 'perfect-fit-solutions', 'perfect-fit-solutions-de');

-- --------------------------------------------------------

--
-- Table structure for table `disciplines`
--

CREATE TABLE `disciplines` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name_de` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description_de` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug_de` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `picture` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `disciplines`
--

INSERT INTO `disciplines` (`id`, `name`, `name_de`, `description_de`, `description`, `slug`, `slug_de`, `picture`) VALUES
(1, 'Business Studies & Business Management', 'Wirtschaftswissenschaften & BWL', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'business-studies-business-management', 'wirtschaftswissenschaften-bwl', 'business_studies_and_business_managment.png'),
(2, 'Economics', 'Volkswirtschaftslehre (VWL)', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'economics', 'volkswirtschaftslehre-vwl', 'economics.png'),
(3, 'Financial Science', 'Finanzwissenschaften', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'financial-science', 'finanzwissenschaften', 'financial_science.png'),
(4, 'Law', 'Rechtswissenschaften', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'law', 'rechtswissenschaften', 'law.png'),
(5, 'Computer Science & Mathematics', 'Informatik & Mathematik', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'computer-science-mathematics', 'informatik-mathematik', 'computer_science.png'),
(6, 'Engineering & Technology', 'Ingenieurwesen &Technik', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'engineering-technology', 'ingenieurwesen-technik', 'engineering_and_technology.png'),
(7, 'Architecture', 'Architektur', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'architecture', 'architektur', 'architecture.png'),
(8, 'Arts, Design & Music', 'Kunst, Gestaltung & Musik', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'arts-design-music', 'kunst-gestaltung-musik', 'art_design_and_music.png'),
(9, 'Literary Studies & German Studies', 'Literaturwissenschaft & Germanistik', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', 'literary-studies-german-studies', 'literaturwissenschaften-germanistik', 'literary_studies_and_german_studies.png'),
(10, 'Philosophy & History', 'Philosophie & Geschichte', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'philosophy-history', 'philosophie-geschichte', 'phylosophy_and_history.png'),
(11, 'Linguistics & Cultural Studies', 'Sprach- & Kulturwissenschaften', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', 'linguistics-cultural-studies', 'sprachwissenschaften-kulturwissenschaften', 'linguistics_and_culture_studies.png'),
(12, 'Political Science', 'Politikwissenschaften', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'political-science', 'politikwissenschaften', 'political_science.png'),
(13, 'Education & Pedagogy', 'Bildung & Erziehung', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'education-pedagogy', 'bildung-erziehung', 'education_and_pedagogy.png'),
(14, 'Media & Communication', 'Medien & Kommunikation', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'media-communication', 'medien-kommunikation', 'media_and_communication.png'),
(15, 'Social Sciences', 'Sozialwissenschaften', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'social-sciences', 'sozialwissenschaften', 'social_sciences.png'),
(16, 'Social work', 'Soziale Arbeit', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'social-work', 'soziale-arbeit', 'social_work.png'),
(17, 'Sociology', 'Soziologie', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'sociology', 'soziologie', 'sociology.png'),
(18, 'Agriculture & Forestry', 'Agrar- & Forstwissenschaften', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'agriculture-forestry', 'agrar-forstwissenschaften', 'agriculture_and_forestry.png'),
(19, 'Biology', 'Biologie', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'biology', 'biologie', 'biology.png'),
(20, 'Chemistry', 'Chemie', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'chemistry', 'chemie', 'chemistry.png'),
(21, 'Medicine & Public Health', 'Medizin & Öffentliche Gesundheit', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'medicine-public-health', 'medizin-offentliche-gesundheit', 'medicine_and_public_health.png'),
(22, 'Dental Medicine', 'Zahnmedizin', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'dental-medicine', 'zahnmedizin', 'dental_medicine.png'),
(23, 'Nursing Science', 'Pflegewissenschaften', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'nursing-science', 'pflegewissenschaften', 'nursing_science.png'),
(24, 'Psychology', 'Psychologie', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'psychology', 'psychologie', 'psychology.png');

-- --------------------------------------------------------

--
-- Table structure for table `services`
--

CREATE TABLE `services` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name_de` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description_de` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug_de` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `picture` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `services`
--

INSERT INTO `services` (`id`, `name`, `name_de`, `description_de`, `description`, `slug`, `slug_de`, `picture`) VALUES
(1, 'Literature Research', 'Literaturrecherche', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'literature-research', 'literaturrecherche', 'literature_research.png'),
(2, 'Topic Proposal', 'Themenvorschlag', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'topic-proposal', 'themenvorschlag', 'topic_proposal.png'),
(3, 'Outline', 'Gliederung', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'outline', 'gliederung', 'outline.png'),
(4, 'Exposé / Proposal', 'Exposé / Proposal', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'expose-proposal', 'expose-proposal', 'expose.png'),
(5, 'Capstone Paper', 'Capstone-Paper', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'capstone-paper', 'capstone-paper', 'capstone_paper.png'),
(6, 'Essay', 'Essay', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'essay', 'essay', 'essay.png'),
(7, 'Term Paper & Seminar Paper', 'Hausarbeit & Seminararbeit', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'term-paper-seminar-paper', 'hausarbeit-seminararbeit', 'term_and_seminar_paper.png'),
(8, 'Legal Term Paper', 'Juristische Gutachten', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'legal-term-paper', 'juristische-gutachten', 'legal_term_paper.png'),
(9, 'Project Thesis', 'Projektarbeit', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'project-thesis', 'projektarbeit', 'project_thesis.png'),
(10, 'Diploma Thesis', 'Diplomarbeit', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'diploma-thesis', 'diplomarbeit', 'diploma_thesis.png'),
(11, 'Bachelor Thesis', 'Bachelorarbeit', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'bachelor-thesis', 'bachelorarbeit', 'bachelor_thesis.png'),
(12, 'Master Thesis', 'Masterarbeit', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'master-thesis', 'masterarbeit', 'master_thersis.png'),
(13, 'Magister Thesis', 'Magisterarbeit', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'magister-thesis', 'magisterarbeit', 'magister_thesis.png'),
(14, 'State Examination Thesis', 'Staatsexamensarbeit', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'state-examination-thesis', 'staatsexamensarbeit', 'state_examination.png'),
(15, 'CAS Thesis', 'CAS-Arbeit', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'cas-thesis', 'cas-arbeit', 'cas_thesis.png'),
(16, 'Doctoral Thesis & PhD Thesis', 'Doktorarbeit & PhD-Arbeit', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'doctoral-thesis-phd-thesis', 'doktorarbeit-phd-arbeit', 'doctoral_phd_thesis.png'),
(17, 'Disputation', 'Disputation', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'disputation', 'disputation', 'disputation.png'),
(18, 'Doctoral Advisory', 'Promotionsberatung', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'doctoral-advisory', 'promotionsberatung', 'doctoral_advisory.png'),
(19, 'Scientific Article', 'Fachartikel', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'scientific-article', 'fachartikel', 'scientific_article.png'),
(20, 'Abstract', 'Abstract', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'abstract', 'abstract', 'abstact.png'),
(21, 'Summary / Excerpt', 'Zusammenfassung / Exzerpt', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'summary-excerpt', 'zusammenfassung-exzerpt', 'summary_excert.png'),
(22, 'Handout & Powerpoint Presentation', 'Referat & Powerpointpräsentation', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'handout-powerpoint-presentation', 'referat-powerpointprasentation', 'handout_powerpoint_presentation.png'),
(23, 'Corporate Book', 'Corporate Book', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'corporate-book', 'corporate-book', 'corporate_book.png'),
(24, 'Business Plan', 'Businessplan', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'business-plan', 'businessplan', 'business_plan.png'),
(25, 'Market Analysis', 'Marktanalyse', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'market-analysis', 'marktanalyse', 'market_analysis.png'),
(26, 'Case Study', 'Fallstudie', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'case-study', 'fallstudie', 'case_study.png'),
(27, 'Qualitative Interview', 'Qualitatives Interview', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'qualitative-interview', 'qualitatives-interview', 'qualitative_interview.png'),
(28, 'Quantitative Interview', 'Quantitatives Interview', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'quantitative-interview', 'quantitatives-interview', 'quantitative_interview.png'),
(29, 'Scientific Review', 'Wissenschaftliches Review', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'scientific-review', 'wissenschaftliches-review', 'scientific_review.png'),
(30, 'Motivation Letter & Resume', 'Bewerbung & Lebenslauf', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', 'motivation-letter-resume', 'bewerbung-lebenslauf', 'motivation_letter_and_cv.png'),
(31, 'Publisher Publication', 'Verlagsveröffentlichung', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'publisher-publication', 'verlagsveroffentlichung', 'publisher_publication.png'),
(32, 'Peer Review Publication', 'Peer-Review-Veröffentlichung', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'peer-review-publication', 'peer-review-veroffentlichung', 'peer_review_publication.png'),
(33, 'Translations', 'Übersetzungen', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'translations', 'ubersetzungen', 'translations.png'),
(34, 'Statistical Analysis', 'Statistische Auswertungen', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'statistical-analysis', 'statistische-auswertungen', 'statistical_analysis.png'),
(35, 'Proofreading', 'Korrektorat', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'proofreading', 'korrektorat', 'proofreading.png'),
(36, 'Editing', 'Lektorat', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'editing', 'lektorat', 'editing.png'),
(37, 'Paraphrasing', 'Paraphrasieren', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'paraphrasing', 'paraphrasieren', 'paraphrasing.png'),
(38, 'Transcriptions', 'Transkriptionen', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'transcriptions', 'transkriptionen', 'transcriptions.png'),
(39, 'Formatting', 'Formatierungsarbeiten', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'formatting', 'formatierungsarbeiten', 'formating.png'),
(40, 'Plagiarism Check', 'Plagiatsprüfung', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n					  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n					  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n					  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n					  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n					  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'plagiarism-check', 'plagiatsprufung', 'plagiarism_check.png');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `about_pages`
--
ALTER TABLE `about_pages`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `disciplines`
--
ALTER TABLE `disciplines`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `services`
--
ALTER TABLE `services`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `about_pages`
--
ALTER TABLE `about_pages`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `disciplines`
--
ALTER TABLE `disciplines`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=25;

--
-- AUTO_INCREMENT for table `services`
--
ALTER TABLE `services`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=41;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
